# Generated by Django 3.2 on 2021-04-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('mail', models.EmailField(max_length=100, verbose_name='Почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.status', verbose_name='Статус')),
            ],
        ),
    ]
