# Generated by Django 3.2 on 2021-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210419_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.CharField(default=0, max_length=100, verbose_name='Время занятий'),
            preserve_default=False,
        ),
    ]
