# Generated by Django 3.2 on 2021-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210420_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Свободное время'),
        ),
    ]
