# Generated by Django 3.2 on 2021-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210425_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=1, max_length=13, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
